# Generated by Django 2.1 on 2018-08-12 04:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='author',
            new_name='auth_user',
        ),
        migrations.AddField(
            model_name='tweet',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 12, 4, 32, 11, 559158, tzinfo=utc)),
        ),
    ]
